### ISSUE TITLE
Payment details: data input is only captured via Carriage Return (CR)

### ISSUE THREAD

**Issue by marcalwestf** [erpcya/AD-POS-WebUI#11]
1.- Select an order to pay
2.- Press the payment button
3- Add a credit card tender type
4.- type in a correct credit card number. Accept it by pressing the OK button.
5.- type in all other data by entering the Carriage Return (CR) key.
6.- press the OK key to start the payment process.
Result: the message not valid" pops up, though it is visible in the window.
See image attached.

The inputs must be captured not only by CR, but also by Tabulator or losing focus.

![20150928_pos_01](https://cloud.githubusercontent.com/assets/1789408/10151611/7fda7690-6606-11e5-8ffd-38d1bf9c3051.png)

**Comment by marcalwestf** [comment]
All other input fields capture data only via Carriage Return, too.

**Comment by yamelsenih** [comment]
Hi Mario, this bug is produced by bad initialization of credit card type in VCollectDetail Class
