### ISSUE TITLE
Payment window not show icons

### ISSUE THREAD

**Issue by e-Evolution** [erpcya/AD-POS-WebUI#3]
The current payment info not show some content 

<img width="454" alt="paymentwindow" src="https://cloud.githubusercontent.com/assets/786968/9978824/1627ebe8-5f11-11e5-8759-52b0e613df2f.png">

**Comment by yamelsenih** [comment]
Hi Victor, it issue is fixed in https://github.com/erpcya/AD-POS-WebUI/commit/127ddae8e3c9244255c4db342b55595dead21902 review.

**Comment by marcalwestf** [comment]
confirmed
