### ISSUE TITLE
The text input not work

### ISSUE THREAD

**Issue by e-Evolution** [erpcya/AD-POS-WebUI#4]
1.- I set an product for example patio set or any other , this show product name but when entry not add of product basket line

**Comment by yamelsenih** [comment]
Hi Victor, this is worked, i find with the name:Patio Furn or with the Value patioset.

**Comment by e-Evolution** [comment]
Hi Yamel , I also find but when try set entry not add the  basket line

**Comment by yamelsenih** [comment]
it have a issue when show the Query Product and select a item, this not worked. I fixed the bug and will commit

**Comment by yamelsenih** [comment]
Hi Victor, its issue is fixed in https://github.com/erpcya/AD-POS-WebUI/commit/c126a6771b6e79bff3464a2503984175e843d7b7
