### ISSUE TITLE
Payment Dialog "forgets" payments already done when adding payment tender types

### ISSUE THREAD

**Issue by marcalwestf** [erpcya/AD-POS-WebUI#63]
1.- create an order and add product(s)
2.- open payment dialog, select "Credit sale" and complete the sales
3.- re-open the document and activate the payment dialog.
     Result: the Grand Total, Payment amount, Open amount and Change amount are displayed correctly.
4.- Add a tender type (press the "+" button).
     Result:  Result: the Grand Total, Payment amount, Open amount and Change amount are displayed INCORRECTLY. They seem not to be updated when the "+" is selected.

See images attached.
![20151020_pos_01](https://cloud.githubusercontent.com/assets/1789408/10609675/03bd3676-7702-11e5-9dde-a8cf3005abf3.png)
![20151020_pos_02](https://cloud.githubusercontent.com/assets/1789408/10609676/03c2444a-7702-11e5-816b-f35dfee6a07d.png)

**Comment by yamelsenih** [comment]
Its behavior is normal, is correct, the "Payment Amount" field show the amount paid to document, when you add a new payment, its is added to payment amount, in detail:
1- Before add a new payment:
   * Grand Total = 159.52
   * Payment Amount = 55.92
   * Open = 103.60
2- After Add a new payment:
   * Grand Total = 159.52 (Never Change).
   * Payment Amount = 159.52 (this is: 55.92[Old Payment] + 103.60 [new payment]).
   * Open = 0 (this is: [Grand Total] - [Old Payment] - [new Payment])

**Comment by marcalwestf** [comment]
it is OK, you have to type in an amount to see how the amounts change.
I close the issue.
