### ISSUE TITLE
When add a product and need change business partner not is allow

### ISSUE THREAD

**Issue by e-Evolution** [erpcya/AD-POS-WebUI#9]
1.- Add new product , next I need to change of business partner, but this not is possible.
When a business partner change we need check of global discount and price list to recalculate and refresh basket information

**Comment by marcalwestf** [comment]
I think with the actual implementation this is not an error, but a feature.
If the business partner is changed, the price list can contain or not the products in the order. Also, the price list prices may differ and the line may have a discount. This would be very difficult to solve automatically. 
Thus, unless there is a thorough solution, is is more robust to allow changing the business partner only if there are no lines.

**Comment by yamelsenih** [comment]
Hi guys, this feature is added.
